#!/bin/bash

rm -r profiling_O0
mkdir profiling_O0

rm gmon.out
gcc profile_main.c SVD.c SVD_matrix.c SVD_math.c -lc -lm -marm -mfloat-abi=hard -mfpu=neon -O0 -pg -o gprof_profile_main_O0
./gprof_profile_main_O0
gprof gprof_profile_main_O0 gmon.out > ./profiling_O0/gprof_profile_main_data_O0.txt
rm gmon.out
rm ./gprof_profile_main_O0

gcc profile_main.c SVD.c SVD_matrix.c SVD_math.c -lc -lm -marm -mfloat-abi=hard -mfpu=neon -DTIME_TEST -O0 -o time_profile_main_O0
./time_profile_main_O0 > ./profiling_O0/time_profile_main_O0.txt
rm ./time_profile_main_O0

rm ./callgrind.out.*
gcc main.c SVD.c SVD_matrix.c SVD_math.c -lm -marm -mfloat-abi=hard -mfpu=neon -O0 -o callgrind_profile_main_O0
valgrind --tool=callgrind ./callgrind_profile_main_O0
log_file=$(find . -name 'callgrind.out.*')
callgrind_annotate --auto=yes --inclusive=no $log_file > ./profiling_O0/callgrind_profile_main_O0_exclusive.txt
callgrind_annotate --auto=yes --inclusive=yes $log_file > ./profiling_O0/callgrind_profile_main_O0_inclusive.txt
rm ./callgrind.out.*
rm ./callgrind_profile_main_O0

cd profiling_O0
mkdir assembly
cd assembly
gcc ../../main.c ../../SVD.c ../../SVD_matrix.c ../../SVD_math.c -ln -marm -mfloat-abi=hard -mfpu=neon -O0 -S
cd ..
cd ..
